# Example scraper to demonstrate Memorious XPath narrowing
name: article_scraper
description: Articles to scrape
# Uncomment to run this scraper automatically:
# schedule: weekly
pipeline:
  init:
    # Start URL
    method: seed
    params:
      urls:
        - https://www.occrp.org/en/investigations
    handle:
      pass: fetch
  fetch:
    # Download the page passed from the seed stage.
    method: fetch
    handle:
      pass: parse
  parse:
    method: example.article:parse
    params:
      schema: article
      properties:
        title: .//title/text()
        author: .//div[@class="by"]/strong/text()
        publishedAt: .//div[@class="date"]/text()
        description: .//meta[@name="description"]/@content
      match:
        or:
          - pattern: .*stories.*
          - xpath: .//div[@class="occrp-page"]
    handle:
      store: store
  store:
    # Store the crawled documents to a directory
    method: aleph_entity
    params:
      path: /data/results