version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: servicelayer[amazon,google]
    versions:
    - 1.17.0
    - 1.17.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
    - 3.13.2
